feat(LT-3316): add api for rfq monitoring with taking data from db
LykkeBusiness/MT pull request #336
Opened 2021-05-24 09:45 UTC by IuriiAksenov

2021-05-24 10:01 UTC, tarurar requested changes

2021-05-24 10:01 UTC, tarurar commented on src/MarginTrading.SqlRepositories/Repositories/OperationExecutionInfoRepository.cs
> +            const int MaxResults = 1000;
I think 1000 is too much. Let's make it 100.

2021-05-24 10:43 UTC, IuriiAksenov commented on src/MarginTrading.Backend/Controllers/RfqController.cs
> +                CreatedBy = string.IsNullOrEmpty(operation.Data.AdditionalInfo) ? null : JsonConvert.DeserializeObject<AdditionalInfo>(operation.Data.AdditionalInfo).CreatedBy,
IsOnBehalf duplicates OriginatorType, when IsOnBehalf true OriginatorType has also OnBehalf value

2021-05-24 10:43 UTC, IuriiAksenov commented on src/MarginTrading.Backend/Controllers/RfqController.cs
> +            var states = getRfqRequest.States?.Select(x => (SpecialLiquidationOperationState)x).ToList();
Added

2021-05-24 10:43 UTC, IuriiAksenov commented on src/MarginTrading.SqlRepositories/Repositories/OperationExecutionInfoRepository.cs
> +            const int MaxResults = 1000;
Fixed

2021-05-24 10:56 UTC, tarurar approved these changes

2021-06-01 08:19 UTC, gponomarev-lykke approved these changes

2021-06-01 08:36 UTC, merged