Lt 3436 negative protection compensates too much
LykkeBusiness/MT pull request #342
Opened 2021-07-23 15:19 UTC by tarurar

2021-08-02 10:04 UTC, evgshk approved these changes

2021-08-02 10:57 UTC, gponomarev-lykke submitted a review, later dismissed

2021-08-02 12:04 UTC, anokhin-lkk requested changes

2021-08-02 12:04 UTC, anokhin-lkk commented on src/MarginTrading.Common/Extensions/EnumerableExtensions.cs
> +                .ToDictionary(m => m.Rank, m => m.Element));
I am not 100% sure that this method works as expected, considering this https://stackoverflow.com/questions/204505/preserving-order-with-linq.
At least we should have tests here for sure. 
We need tests for such methods and also we should write tests for different scenarios to make sure that implemented logic indeed works. It is very difficult to test such scenarios manually.

Overall I think that you should not change PositionsCloseData at all, but simply add order explicitly directly in ClosePositionsAsync. In the way how it is implemented right now, you have too many iterations and remapping of the list between the ordering and final iteration and I am not sure that now or at some point in the future it will not be broken. 
At the same time, there is only 1 place in the code when the order indeed matters - when you finally iterate through positions, close each position and produce event to change P&L.

And ... I just realized that this part is not implemented at all, because it should be done here https://github.com/LykkeBusiness/MT/blob/master/src/MarginTrading.Backend.Services/EventsConsumers/PositionsConsumer.cs#L182.
That's why tests are very important here )
So, as a conclusion, you in fact should use LargestPnlFirst() only in  PositionsConsumer...

2021-08-03 14:01 UTC, anokhin-lkk approved these changes

2021-08-03 14:03 UTC, merged