[LT-4383] Update Account Change to change ClientProfile
LykkeBusiness/MT pull request #420
Opened 2023-01-20 10:06 UTC by fatihdumanli

[LT-4383](https://lykke-snow.atlassian.net/browse/LT-4383)

- Upgrade Lykke.MarginTrading.AccountsManagment.Contracts package to 7.8.0 to include **ClientModificationTimestamp** in AccountContract

Update account cache to update **TradingCondition** for account.

2023-01-20 11:50 UTC, tarurar requested changes

2023-01-20 11:50 UTC, tarurar commented on src/MarginTrading.Backend.Core/IMarginTradingAccount.cs
> +        public DateTime ClientModificationTimestamp { get; set; }
I don't think it is a good idea to have 2 timestamp for latest account update. I think the existing LastUpdateTime is enough.

2023-01-20 11:50 UTC, tarurar commented on src/MarginTrading.Backend.Services/Services/AccountsCacheService.cs
> +            DateTime eventTime, string additionalInfo, DateTime clientModificationTimestamp)
```suggestion
            DateTime eventTime, string additionalInfo, DateTime originalModificationTimestamp)
```

2023-01-20 11:50 UTC, tarurar commented on src/MarginTrading.Backend.Services/Services/AccountsCacheService.cs
> +
```suggestion
```

2023-01-20 11:50 UTC, tarurar commented on src/MarginTrading.Backend.Services/Workflow/AccountsProjection.cs
> +                                    updatedAccount.AdditionalInfo, e.Account.ClientModificationTimestamp))
```suggestion
                                    updatedAccount.AdditionalInfo, MaxOf(e.Account.ClientModificationTimestamp, e.Account.ModificationTimestamp))
```

2023-01-20 11:50 UTC, tarurar commented on src/MarginTrading.Backend.Services/Services/AccountsCacheService.cs
```suggestion
                if (account.LastUpdateTime < originalModificationTimestamp)
                {
```

2023-01-20 11:50 UTC, tarurar commented on src/MarginTrading.Backend.Services/Services/AccountsCacheService.cs
> -                account.TradingConditionId = updatedTradingConditionId;
no need to remove

2023-01-20 11:50 UTC, tarurar commented on src/MarginTrading.Backend.Services/Services/AccountsCacheService.cs
>                  account.IsWithdrawalDisabled = isWithdrawalDisabled;
```suggestion
                account.IsWithdrawalDisabled = isWithdrawalDisabled;
              }
```

2023-01-20 13:21 UTC, fatihdumanli commented on src/MarginTrading.Backend.Core/IMarginTradingAccount.cs
> +        public DateTime ClientModificationTimestamp { get; set; }
Property removed.

2023-01-20 13:24 UTC, fatihdumanli commented on src/MarginTrading.Backend.Services/Services/AccountsCacheService.cs
> +            DateTime eventTime, string additionalInfo, DateTime clientModificationTimestamp)
I removed this property as we discussed. **eventTime** is just an alias for **account.ModificationTimestamp** so we can pass **Max(e.ChangeTimeStamp, e.Account.ClientModificationTimestamp)** as **eventTime** argument to this function.

2023-01-20 14:17 UTC, tarurar commented on src/MarginTrading.Backend.Services/Workflow/AccountsProjection.cs
> +                                    DateTimeExtensions.MaxDateTime(e.ChangeTimestamp, e.Account.ClientModificationTimestamp),
Is `e.ChangeTimestamp` an account modification timestamp?

2023-01-20 14:17 UTC, tarurar commented on src/MarginTrading.Backend.Core/Extensions/DateTimeExtensions.cs
> +        public static DateTime MaxDateTime(DateTime first, DateTime second)
What about unit tests?

2023-01-20 14:17 UTC, tarurar commented on src/MarginTrading.Backend.Services/Workflow/AccountsProjection.cs
> +                                    DateTimeExtensions.MaxDateTime(e.ChangeTimestamp, e.Account.ClientModificationTimestamp),
Can you also add a unit test which will ensure that the max of dates will be taken and passed into `_accountsCacheService.UpdateAccountChanges`?

2023-01-23 06:26 UTC, fatihdumanli commented on src/MarginTrading.Backend.Services/Workflow/AccountsProjection.cs
> +                                    DateTimeExtensions.MaxDateTime(e.ChangeTimestamp, e.Account.ClientModificationTimestamp),
> Is `e.ChangeTimestamp` an account modification timestamp?

Yes. It's, it's set to **account.ModificationTimestamp in AM** https://github.com/LykkeBusiness/MarginTrading.AccountsManagement/blob/02607c0271c67fc4343c49f760d63a8aa5811c4e/src/MarginTrading.AccountsManagement/Services/Implementation/EventSender.cs#L45


> Can you also add a unit test which will ensure that the max of dates will be taken and passed into `_accountsCacheService.UpdateAccountChanges`?

Unit tests are added to verify that we call **_accountsCacheService.UpdateAccountChanges** with the most recent timetsamp.

2023-01-23 06:26 UTC, fatihdumanli commented on src/MarginTrading.Backend.Core/Extensions/DateTimeExtensions.cs
> +        public static DateTime MaxDateTime(DateTime first, DateTime second)
Unit tests are added.

2023-01-23 08:18 UTC, tarurar commented on tests/MarginTradingTests/AccountsProjectionTests.cs
> +            if (changeTimestamp > clientModificationTimestamp)
Why not use here your `MaxDateTime` function?

2023-01-23 08:24 UTC, fatihdumanli commented on tests/MarginTradingTests/AccountsProjectionTests.cs
> +            if (changeTimestamp > clientModificationTimestamp)
We could. My thought was to cross-check both functions.

If we had relied on **MaxDateTime** function on this test, even **MaxDateTime** returns invalid data, this function would still pass. This is like cross-checking to make sure **MaxDateTime** works fine and `_accountCacheService.UpdateAccountCache()` is called with the greater timestamp.

2023-01-23 08:45 UTC, tarurar commented on tests/MarginTradingTests/AccountsProjectionTests.cs
> +            if (changeTimestamp > clientModificationTimestamp)
Well, no. Each test has a goal. Mixing goals is a bad idea. For MaxDateTime function you already has unit test which covers it. It means you can use that function.

2023-01-23 08:58 UTC, fatihdumanli commented on tests/MarginTradingTests/AccountsProjectionTests.cs
> +            if (changeTimestamp > clientModificationTimestamp)
I get your point, but isn't mixing the goals exactly what the integration tests are for?

2023-01-23 08:58 UTC, anokhin-lkk commented on src/MarginTrading.Backend.Services/Workflow/AccountsProjection.cs
> +                                    DateTimeExtensions.MaxDateTime(e.ChangeTimestamp, e.Account.ClientModificationTimestamp),
Well... That's not good that we comparing e.Account.ClientModificationTimestamp and e.ChangeTimestamp, but not e.Account.ModificationTimestamp. The idea of e.ChangeTimestamp is to store the timestamp of the event. And now I am thinking that this is the actual issue:
https://github.com/LykkeBusiness/MarginTrading.AccountsManagement/blob/02607c0271c67fc4343c49f760d63a8aa5811c4e/src/MarginTrading.AccountsManagement/Services/Implementation/EventSender.cs#L45
We are using account modification timestamp as an event timestamp, but if we will be using DateTime.UtcNow it would solve the issue. I am not sure about side effects but for me it looks that you guys @tarurar and @fatihdumanli overcomplicated this task a lot.

2023-01-23 09:00 UTC, tarurar commented on tests/MarginTradingTests/AccountsProjectionTests.cs
> +            if (changeTimestamp > clientModificationTimestamp)
This one hardly can be called "integration test". You are testing just a single line of code.

2023-01-23 09:10 UTC, fatihdumanli commented on src/MarginTrading.Backend.Services/Workflow/AccountsProjection.cs
> +                                    DateTimeExtensions.MaxDateTime(e.ChangeTimestamp, e.Account.ClientModificationTimestamp),
Well, I'm also not sure about the side effects. But this development is done and defensive and safe, not likely to break anything. If @tarurar agrees we can replace it with `DateTime.UtcNow` but like I said this development is already done and I think it's safer than making such a change.

2023-01-23 09:25 UTC, tarurar commented on src/MarginTrading.Backend.Services/Workflow/AccountsProjection.cs
> +                                    DateTimeExtensions.MaxDateTime(e.ChangeTimestamp, e.Account.ClientModificationTimestamp),
I agree with the part related to AM, it is semantically wrong to put account change timestamp into the filed where event timestamp should be, still it is related to Account Management pull request. @fatihdumanli we can discuss AM PR separately.

2023-01-23 09:26 UTC, tarurar submitted a review, later dismissed

2023-01-23 12:58 UTC, tarurar commented on tests/MarginTradingTests/AccountsProjectionTests.cs
> +        public async Task UpdateAccountCache_ShouldBeCalledWith_TheMostRecentTimestamp_Successfully(string changeTimeStr, string clientModificationTimestampStr)
I think to be clearer we better rename the changeTimeStr:
```suggestion
        public async Task UpdateAccountCache_ShouldBeCalledWith_TheMostRecentTimestamp_Successfully(string accountModificationTimestampStr, string clientModificationTimestampStr)

```

2023-01-23 13:35 UTC, fatihdumanli commented on tests/MarginTradingTests/AccountsProjectionTests.cs
> +        public async Task UpdateAccountCache_ShouldBeCalledWith_TheMostRecentTimestamp_Successfully(string changeTimeStr, string clientModificationTimestampStr)
Renamed accordingly

2023-01-23 15:47 UTC, merged