Lt 4940 notional validation
LykkeBusiness/MT pull request #452
Opened 2023-08-07 14:48 UTC by lykke-vashetsin

2023-08-18 12:02 UTC, fatihdumanli commented on src/MarginTrading.Backend.Core/DealManager.cs
> +            if (maxPositionNotional.HasValue)
I'd say a brief description that describes the thought process here would be beneficial for better understanding.

2023-08-18 12:02 UTC, fatihdumanli commented on src/MarginTrading.Backend.Core/DealManager.cs
> +                LogLocator.CommonLog.Info($"Temp log for MaxPositionNotional: {JsonConvert.SerializeObject(tempLogObj)}");
Do we need to remove this temp log?

2023-08-18 12:36 UTC, tarurar requested changes

2023-08-18 12:36 UTC, tarurar commented on src/MarginTrading.Backend.Core/DealManager.cs
> +            decimal? maxPositionNotional,
New parameters not added to description

2023-08-18 12:36 UTC, tarurar commented on src/MarginTrading.Backend.Core/DealManager.cs
> +            if (maxPositionNotional.HasValue)
I agree, the core idea behind max position notional should be clear.

2023-08-18 12:36 UTC, tarurar commented on src/MarginTrading.Backend.Services/Services/OrderValidator.cs
> +            if (!_quoteCashService.TryGetQuoteById(
Don't we already have this validation in `ValidateBaseOrderPrice`?

2023-08-21 09:33 UTC, lykke-vashetsin commented on src/MarginTrading.Backend.Core/DealManager.cs
> +                LogLocator.CommonLog.Info($"Temp log for MaxPositionNotional: {JsonConvert.SerializeObject(tempLogObj)}");
yes, these are temporary for QA during testing

2023-08-21 09:42 UTC, lykke-vashetsin commented on src/MarginTrading.Backend.Services/Services/OrderValidator.cs
> +            if (!_quoteCashService.TryGetQuoteById(
yes, I've seen but my thought was that it is not clear that this validation happens just before calling public 'PreTradeValidate' method.
Should I replace with
var quote = _quoteCashService.GetQuote(orderFulfillmentPlan.Order.AssetPairId);
instead?

2023-08-21 09:44 UTC, lykke-vashetsin commented on src/MarginTrading.Backend.Core/DealManager.cs
> +            if (maxPositionNotional.HasValue)
@tarurar, @fatihdumanli, would it be fine if I leave a link to docs where formulas explained in details?

2023-08-21 09:45 UTC, lykke-vashetsin commented on src/MarginTrading.Backend.Core/DealManager.cs
> +            decimal? maxPositionNotional,
done

2023-08-23 06:48 UTC, fatihdumanli commented on src/MarginTrading.Backend.Core/DealManager.cs
> +            if (maxPositionNotional.HasValue)
I am not aware of this doc, but my concern is it's going to be a difficult for some other developer to maintain this code if some matter arises. If you think that document shed light on this logic, please do.

2023-08-24 08:55 UTC, fatihdumanli commented on src/MarginTrading.Backend.Core/DealManager.cs
> +            if (maxPositionNotional.HasValue)
It still seems to be not clear how exactly the logic works. Can you please elaborate the thought process? 

I meant, what is the logic for calculating it? I'd add step by step comments, otherwise, It'd be real challenging for another developer to maintain this code.

2023-08-24 08:56 UTC, fatihdumanli requested changes
Can you please elaborate thought process on calculation logic?

2023-08-24 09:29 UTC, fatihdumanli submitted a review, later dismissed

2023-08-24 10:03 UTC, tarurar approved these changes

2023-08-24 10:12 UTC, merged