fix(LT-5508): orders and positions are fixed during state validation
LykkeBusiness/MT pull request #526
Opened 2024-05-28 08:16 UTC by gponomarev-lykke

- orders and positions are fixed during state validation
- the fixed values are then used to create a draft snapshot
- a retry policy added so the "trading data snapshot might be corrupted" fatal errors should be less frequent

2024-05-28 08:34 UTC, anokhin-lkk requested changes

2024-05-28 08:34 UTC, anokhin-lkk commented on src/MarginTrading.Backend.Core/Orders/IOrderReader.cs
> +    public interface IOrderReader
Maybe we should have a dedicated interface for InMemorySnapshot?
Something like IOrderReader: IOrderReaderBase, where IOrderReaderBase has only 2 required methods?

2024-05-28 08:34 UTC, anokhin-lkk commented on src/MarginTrading.Backend.Services/Infrastructure/SnapshotService.cs
> +                await _log.WriteFatalErrorAsync(nameof(SnapshotService),
In case of not valid result we still will have a fatal error I think. Ant this will happen on every retry. Is that expected? And if yes, why?

2024-05-28 08:34 UTC, anokhin-lkk commented on src/MarginTrading.Backend.Services/Infrastructure/SnapshotService.cs
> +            return validationResult;
Also SnapshotStateValidationPolicy will retry on exceprion, but this method will not throw an exception.

2025-02-05 08:29 UTC, tarurar commented
This PR is outdated, the required one already merged in.

2025-02-05 08:29 UTC, closed without merging